num_envs: 20
max_steps: 100
max_buffer_size: 200000
epochs: 100
eval_frequence: 20
encoder_layers:
  - 256
  - 256
  - 256
actor_layers:
  - 256
  - 256
  - 256
critic_layers:
  - 256
  - 256
  - 256
encoder_dropout_prob: 0.2
learning_rate: 3.0e-4
update_iteration: 100
batch_size: 1000
gamma: 0.95
tau: 0.005
std: 1.0
regularization_weight: 1.0e-2
