num_envs: 20
max_steps: 100
max_buffer_size: 500000
epochs: 250
eval_frequence: 50
encoder_layers:
  - 256
  - 256
  - 256
actor_layers:
  - 256
  - 256
critic_layers:
  - 256
  - 256
encoder_dropout_prob: 0.2
learning_rate: 3.0e-4
update_iteration: 200
batch_size: 1000
gamma: 0.98
tau: 0.005
std: 1.0
regularization_weight: 1.0e-3