num_envs: 20
max_steps: 250
epochs: 200
eval_frequence: 40
encoder_layers:
  - 256
  - 256
  - 256
  - 256
actor_layers:
  - 256
  - 256
critic_layers:
  - 256
  - 256
encoder_dropout_prob: 0.2
learning_rate: 3.0e-4
update_iteration: 25
batch_size: 1000
gamma: 0.98
lambda_: 0.90
value_loss_weight: 0.5
entropy_weight: 0.01
max_grad_norm: 0.5
clip_ratio: 0.2
regularization_weight: 0.0